import { useEffect, useState } from "react";
import {
  PieChart,
  Pie,
  Cell,
  Tooltip,
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Legend,
  LineChart,
  Line,
} from "recharts";
import { AlertTriangle, CheckCircle2, Info, TrendingUp, Sparkles, RefreshCw } from "lucide-react";
import { api } from "../api/client";
import { useAppStore } from "../store/useAppStore";
import { Card, SectionTitle, Button } from "../components/ui";
import { CategoryIcon } from "../components/CategoryIcon";
import { formatCurrency, monthLabel } from "../lib/format";
import type { AnalyticsResponse, AiInsight, AiStatus } from "../types";

const TONE_ICON: Record<string, any> = { info: Info, success: CheckCircle2, warning: AlertTriangle, danger: AlertTriangle };
const TONE_COLOR: Record<string, string> = {
  info: "text-cyan-300 bg-cyan-500/10 border-cyan-400/20",
  success: "text-emerald-300 bg-emerald-500/10 border-emerald-400/20",
  warning: "text-amber-300 bg-amber-500/10 border-amber-400/20",
  danger: "text-rose-300 bg-rose-500/10 border-rose-400/20",
};

export function Analytics() {
  const settings = useAppStore((s) => s.settings);
  const pushToast = useAppStore((s) => s.pushToast);
  const [data, setData] = useState<AnalyticsResponse | null>(null);
  const [range, setRange] = useState(6);
  const [aiStatus, setAiStatus] = useState<AiStatus | null>(null);
  const [aiInsights, setAiInsights] = useState<AiInsight[] | null>(null);
  const [aiLoading, setAiLoading] = useState(false);

  useEffect(() => {
    api.getAnalytics(range).then(setData);
  }, [range]);

  useEffect(() => {
    api.getAiStatus().then(setAiStatus).catch(() => setAiStatus({ enabled: false, model: null }));
  }, []);

  async function loadAiInsights() {
    setAiLoading(true);
    try {
      const res = await api.getAiInsights();
      setAiInsights(res.insights);
    } catch (err) {
      pushToast((err as Error).message, "error");
      setAiInsights([]);
    } finally {
      setAiLoading(false);
      api.getAiStatus().then(setAiStatus).catch(() => {});
    }
  }

  if (!data) return <div className="text-white/40 text-sm">Loading analytics…</div>;

  const cur = settings?.currency || "₹";
  const pieData = data.breakdownRecent.rows.map((r) => ({ name: r.category, value: r.total, color: r.color }));
  const trendData = data.trend.map((t) => ({ month: monthLabel(t.month), Salary: t.salary, Spent: t.spent, Savings: t.savings }));
  const splitData = (data.cycleSplit || []).map((row) => ({ label: row.label, amount: row.amount, color: row.color }));

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-bold text-white tracking-tight">Analytics</h1>
          <p className="text-white/45 text-sm mt-1">Where your money actually goes, and how to save more of it.</p>
        </div>
        <div className="flex gap-1.5 glass rounded-xl p-1">
          {[3, 6, 12].map((r) => (
            <button
              key={r}
              onClick={() => setRange(r)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
                range === r ? "bg-white/15 text-white" : "text-white/40 hover:text-white/70"
              }`}
            >
              {r}mo
            </button>
          ))}
        </div>
      </div>

      {/* Insights */}
      <Card>
        <SectionTitle subtitle="Rule-based observations from your own data">Smart insights for you</SectionTitle>
        <div className="grid md:grid-cols-2 gap-3">
          {data.insights.map((insight, i) => {
            const Icon = TONE_ICON[insight.type] || Info;
            return (
              <div key={i} className={`rounded-xl border p-4 ${TONE_COLOR[insight.type]}`}>
                <div className="flex items-center gap-2 font-medium text-sm mb-1.5">
                  <Icon size={14} /> {insight.title}
                </div>
                <p className="text-white/60 text-sm leading-relaxed">{insight.message}</p>
              </div>
            );
          })}
        </div>
      </Card>

      {/* AI insights */}
      <Card className="border-violet-400/20 bg-gradient-to-br from-violet-600/10 to-cyan-500/5" strong>
        <SectionTitle
          subtitle={
            aiStatus?.enabled
              ? `Generated by ${aiStatus.model}, on top of your numbers${
                  aiStatus.limits ? ` · ${aiStatus.limits.sharedRemainingToday}/${aiStatus.limits.sharedPerDay} AI requests left today` : ""
                }`
              : "Add an API key to unlock this"
          }
          action={
            aiStatus?.enabled && (
              <Button variant="ghost" size="sm" onClick={loadAiInsights} disabled={aiLoading}>
                <RefreshCw size={13} className={aiLoading ? "animate-spin" : ""} /> {aiInsights ? "Regenerate" : "Generate"}
              </Button>
            )
          }
        >
          <span className="flex items-center gap-2">
            <Sparkles size={16} className="text-violet-300" /> AI coach insights
          </span>
        </SectionTitle>

        {!aiStatus?.enabled ? (
          <p className="text-white/45 text-sm">
            Add <code className="text-white/70">OPENAI_API_KEY</code> to <code className="text-white/70">server/.env</code> (Gemini,
            OpenAI, or any OpenAI-compatible endpoint) to get a few extra, conversational savings tips tailored to your exact numbers.
          </p>
        ) : aiInsights === null ? (
          <div className="text-center py-6">
            <p className="text-white/45 text-sm mb-3">Let AI take a pass over your spending and add a few tailored tips.</p>
            <Button onClick={loadAiInsights} disabled={aiLoading}>
              <Sparkles size={15} /> {aiLoading ? "Thinking…" : "Generate AI insights"}
            </Button>
          </div>
        ) : aiInsights.length === 0 ? (
          <p className="text-white/40 text-sm">No extra tips this time — your rule-based insights above already cover it well.</p>
        ) : (
          <div className="grid md:grid-cols-2 gap-3">
            {aiInsights.map((insight, i) => (
              <div key={i} className="rounded-xl border border-violet-400/20 bg-violet-500/5 p-4">
                <div className="flex items-center gap-2 font-medium text-sm mb-1.5 text-violet-200">
                  <Sparkles size={13} /> {insight.title}
                </div>
                <p className="text-white/65 text-sm leading-relaxed">{insight.message}</p>
              </div>
            ))}
          </div>
        )}
      </Card>

      <div className="grid md:grid-cols-2 gap-4">
        {/* Category breakdown pie */}
        <Card>
          <SectionTitle subtitle={`Last ${range} months`}>Where it's going</SectionTitle>
          {pieData.length === 0 ? (
            <EmptyChart text="Log a few expenses to see your category split." />
          ) : (
            <div className="flex items-center gap-4">
              <ResponsiveContainer width="100%" height={220}>
                <PieChart>
                  <Pie data={pieData} dataKey="value" nameKey="name" innerRadius={55} outerRadius={85} paddingAngle={2}>
                    {pieData.map((entry, i) => (
                      <Cell key={i} fill={entry.color} stroke="rgba(255,255,255,0.08)" />
                    ))}
                  </Pie>
                  <Tooltip
                    contentStyle={{ background: "#141428", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 12, fontSize: 12 }}
                    formatter={(v) => formatCurrency(Number(v), cur)}
                  />
                </PieChart>
              </ResponsiveContainer>
            </div>
          )}
          <div className="mt-2 space-y-1.5 max-h-40 overflow-y-auto scrollbar-thin">
            {data.breakdownRecent.rows.map((r) => (
              <div key={r.category} className="flex items-center gap-2 text-sm">
                <div className="w-6 h-6 rounded-md flex items-center justify-center shrink-0" style={{ backgroundColor: `${r.color}22` }}>
                  <CategoryIcon icon={r.icon} size={11} style={{ color: r.color }} />
                </div>
                <span className="text-white/65 flex-1 truncate">{r.category}</span>
                <span className="text-white/40 text-xs">{r.pct}%</span>
                <span className="text-white/85 font-medium tabular-nums">{formatCurrency(r.total, cur)}</span>
              </div>
            ))}
          </div>
        </Card>

        {/* Balance split: what is already spent, reserved, and free */}
        <Card>
          <SectionTitle subtitle="Spent is already gone. The rest is how today's balance is reserved.">
            Where your money stands
          </SectionTitle>
          {splitData.length === 0 ? (
            <EmptyChart text="Add a salary, balance, or a few expenses to see this split." />
          ) : (
            <>
              <ResponsiveContainer width="100%" height={260}>
                <BarChart data={splitData} layout="vertical" margin={{ left: 8, right: 12 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.06)" horizontal={false} />
                  <XAxis type="number" stroke="rgba(255,255,255,0.25)" fontSize={11} tickLine={false} axisLine={false} />
                  <YAxis type="category" dataKey="label" stroke="rgba(255,255,255,0.45)" fontSize={11} tickLine={false} axisLine={false} width={108} />
                  <Tooltip
                    contentStyle={{ background: "#141428", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 12, fontSize: 12 }}
                    formatter={(v) => formatCurrency(Number(v), cur)}
                    cursor={{ fill: "rgba(255,255,255,0.04)" }}
                  />
                  <Bar dataKey="amount" radius={[0, 6, 6, 0]} barSize={18}>
                    {splitData.map((row) => (
                      <Cell key={row.label} fill={row.color} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
              <div className="mt-2 space-y-1.5">
                {splitData.map((row) => (
                  <div key={row.label} className="flex items-center gap-2 text-sm">
                    <span className="w-2 h-2 rounded-full shrink-0" style={{ backgroundColor: row.color }} />
                    <span className="text-white/65 flex-1">{row.label}</span>
                    <span className="text-white/85 font-medium tabular-nums">{formatCurrency(row.amount, cur)}</span>
                  </div>
                ))}
              </div>
            </>
          )}
        </Card>
      </div>

      {/* Monthly trend */}
      <Card>
        <SectionTitle subtitle="Salary vs. spend vs. savings over time" action={<TrendingUp size={16} className="text-white/30" />}>
          Monthly trend
        </SectionTitle>
        {trendData.length === 0 ? (
          <EmptyChart text="Add past months' data to see long-term trends." />
        ) : (
          <ResponsiveContainer width="100%" height={280}>
            <LineChart data={trendData}>
              <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.06)" vertical={false} />
              <XAxis dataKey="month" stroke="rgba(255,255,255,0.35)" fontSize={12} tickLine={false} axisLine={false} />
              <YAxis stroke="rgba(255,255,255,0.25)" fontSize={11} tickLine={false} axisLine={false} width={50} />
              <Tooltip
                contentStyle={{ background: "#141428", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 12, fontSize: 12 }}
                formatter={(v) => formatCurrency(Number(v), cur)}
              />
              <Legend wrapperStyle={{ fontSize: 12, color: "rgba(255,255,255,0.5)" }} />
              <Line type="monotone" dataKey="Salary" stroke="#67e8f9" strokeWidth={2} dot={{ r: 3 }} />
              <Line type="monotone" dataKey="Spent" stroke="#fb7185" strokeWidth={2} dot={{ r: 3 }} />
              <Line type="monotone" dataKey="Savings" stroke="#a78bfa" strokeWidth={2} dot={{ r: 3 }} />
            </LineChart>
          </ResponsiveContainer>
        )}
      </Card>
    </div>
  );
}

function EmptyChart({ text }: { text: string }) {
  return <div className="h-40 flex items-center justify-center text-sm text-white/30 text-center px-6">{text}</div>;
}
